version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote-calculator-app
    restart: unless-stopped
    ports:
      - "8974:8974"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: php artisan serve --host=0.0.0.0 --port=8974

volumes:
  storage:
  cache:
